# Generated by Django 2.1.3 on 2018-12-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isEmpty', models.BooleanField(default=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_game', to='maingame.Profile')),
                ('participants', models.ManyToManyField(to='maingame.Profile')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_game', to='maingame.Profile')),
            ],
        ),
    ]
