# Generated by Django 2.1.3 on 2018-12-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.BigIntegerField(default=0),
        ),
    ]
