# Generated by Django 2.1.3 on 2018-12-15 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0002_auto_20181215_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='diamonds',
            new_name='gem',
        ),
    ]
