# Generated by Django 2.1.3 on 2018-12-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0002_battle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle_group',
            name='loser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lost_game', to='maingame.Profile'),
        ),
        migrations.AlterField(
            model_name='battle_group',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='won_game', to='maingame.Profile'),
        ),
    ]
