# Generated by Django 2.1.3 on 2018-12-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0003_auto_20181221_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle_group',
            name='category',
            field=models.IntegerField(choices=[(1, 'dices'), (2, 'animal'), (3, 'something')], default=1),
        ),
    ]
