# Generated by Django 2.1.3 on 2018-12-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maingame', '0003_auto_20181216_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', to='maingame.Profile'),
        ),
    ]
