# Generated by Django 2.1.3 on 2018-11-30 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, default='', upload_to='')),
                ('name', models.CharField(default='', max_length=64)),
                ('flag', models.CharField(default='Iran', max_length=16)),
                ('win_strike', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('game_number', models.IntegerField(default=0)),
                ('won_number', models.IntegerField(default=0)),
                ('diamonds', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('friends', models.ManyToManyField(to='maingame.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
